name: npng
description: Fitness and body parameters diary.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+11 # Last AppStore/Play - 11
homepage: https://filonov.pro

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  circular_countdown_timer: ^0.2.0
  flutter_markdown: ^0.6.6
  url_launcher: ^6.0.3
  package_info_plus: ^1.0.1
  audioplayers: ^0.20.0
  equatable: ^2.0.3
  sqflite: ^2.0.0+4
  synchronized: ^3.0.0
  sqlbrite: ^2.1.0
  # json_annotation: ^4.1.0
  path: ^1.8.0
  wakelock: ^0.5.2
  page_transition: ^2.0.2
  cell_calendar: ^0.5.0+1
  share_plus: ^3.0.4 #^2.1.4
  flash: ^2.0.1
  file_picker: ^4.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    #- assets/images/ 
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md
    - assets/db/npng.db

flutter_intl:
  enabled: true
  main_locale: en