name: npng
description: No pain, no gain – fitness and body parameters diary.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1
author: Denis Filonov
homepage: https://filonov.pro

environment:
  sdk: ">=2.7.0 <3.0.0"
  # sdk: ">=2.11.0-213.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^5.0.0-nullsafety.5 #^4.3.3
  #TODO: Find nullsafety analogue. `dart pub outdated --mode=null-safety` 
  # `dart migrate --apply-changes`
  circular_countdown_timer: ^0.2.0
  flutter_markdown: ^0.6.1
  url_launcher: ^5.7.10 #^6.0.3 - Error on building macOS
  package_info_plus: ^0.6.4 #^1.0.0 - Error on building macOS
  # TODO: find package for MacOS
  # audioplayers: ^0.17.1
  convex_bottom_bar: ^3.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 
    - assets/texts/en/
    - assets/texts/ru_RU/
    - assets/sounds/
    - CHANGELOG.md
    - assets/db/en/npng.db

flutter_intl:
  enabled: true
  main_locale: en
