name: npng
description: Crossplatform Workout Tracker.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+15 # Last AppStore 15 /Play 15
homepage: https://filonov.pro/npng-site/

environment:
  sdk: '>=2.17.0 <3.0.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  
  provider: ^6.0.2

  circular_countdown_timer: ^0.2.0
  flutter_markdown: ^0.6.6
  url_launcher: ^6.1.2
  package_info_plus: ^1.0.1
  audioplayers: ^0.20.0
  sqflite: ^2.0.0+4
  sqlbrite: ^2.1.0
  path: ^1.8.0
  path_provider: ^2.0.10
  synchronized: ^3.0.0+2
  wakelock: ^0.6.1+1
  cell_calendar: ^0.6.0
  share_plus: ^4.0.4
  file_picker: ^4.0.1
  shared_preferences: ^2.0.15
  flutter_slidable: ^1.1.0
  steps_indicator: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    #- assets/icons/
    #- assets/images/ 
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md
    - assets/db/npng.db

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true