name: npng
description: No pain, no gain – fitness and body parameters diary.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1
author: Denis Filonov
homepage: https://filonov.pro

environment:
  sdk: ">=2.11.0-213.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+4
  circular_countdown_timer: ^0.0.7
  # multiplatform_widgets:
  #   path: ../multiplatform_widgets/
    # git: 
    #   url: git://github.com/filonov/multiplatform_widgets.git
  flutter_markdown: ^0.4.4
  url_launcher: ^5.5.2
  package_info_plus: ^0.6.3
  # TODO: find package for MacOS
  # audioplayers: ^0.17.1
  convex_bottom_bar: ^2.6.0
  sqflite: ^1.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 
    - assets/texts/en/
    - assets/texts/ru_RU/
    - assets/sounds/
    - CHANGELOG.md

flutter_intl:
  enabled: true
  main_locale: en
