name: npng
description: Crossplatform Workout Tracker.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+15 # Last AppStore 15 /Play 15
homepage: https://filonov.pro/npng-site/

environment:
  sdk: '>=2.17.0 <3.0.1'

dependencies:
  audioplayers: ^1.0.1
  bloc: ^8.1.0
  bloc_test: ^9.0.3
  cell_calendar: ^0.6.0
  circular_countdown_timer: ^0.2.0
  equatable: ^2.0.3
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_slidable: ^2.0.0
  flutter_touch_spin: ^2.0.0
  freezed_annotation: ^2.1.0
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  number_inc_dec: ^0.8.0
  package_info_plus: ^1.0.1
  path: ^1.8.0
  path_provider: ^2.0.10
  provider: ^6.0.2
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  sqlbrite: ^2.3.0
  steps_indicator: ^1.3.0
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.2
  wakelock: ^0.6.1+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icons/
    - assets/images/
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md
    - assets/db/npng.db

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
