name: npng
description: No pain, no gain – fitness and body parameters diary.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+2
author: Denis Filonov
homepage: https://filonov.pro

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  # flutter_bloc: ^7.0.0
  circular_countdown_timer: ^0.2.0
  flutter_markdown: ^0.6.2
  url_launcher: ^6.0.3
  package_info_plus: ^1.0.1
  audioplayers: ^0.19.0
  convex_bottom_bar: ^3.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  wakelock: ^0.5.2
  page_transition: ^2.0.2
  cell_calendar: ^0.5.0+1

dev_dependencies:
  dart_code_metrics: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    #- assets/images/ 
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md
    - assets/db/npng.db

flutter_intl:
  enabled: true
  main_locale: en

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
